# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter_Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: cp /build/app/outputs/flutter-apk/app-release.apk ./
    - run: git add ./app-release.apk
    - run: git commit -m "release"
    - run: git push origin master 
#    - run: flutter build appbundle
