# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter_Android

on:
#  push:
#    branches: [ master ]
  push:
    tags: 'UAT_*'
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.1'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    #- name: get Current Time
    #  run: echo "NOW::$(date + %Y%%d%H%M)" >> $GITHUB_ENV
    ################################################################
    #Push Git    
    - run: cp ./build/app/outputs/flutter-apk/app-release.apk ./release/UAT/uat-release.apk
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'uat release'
        force-add: 'true'
        files: release/UAT/uat-release.apk
        name: UATRelease
        email: heejung.lee@ibexlab.com 
    ################################################################
    #Push GDrive
    #- name: Upaload to gdrive
    #  #uses: adityak74/google-drive-upload-git-action@main
    #  uses: team-tumbleweed/gdrive-upload-action@main
    #  with: 
    #    credentials: "eyAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLCAicHJvamVjdF9pZCI6ICJzbWFydC1vYXNpcy0zNDA2MDEiLCAicHJpdmF0ZV9rZXlfaWQiOiAiNmVkYmY0NzBhOTJiZDFiYzNkNzY2NDEzNjEzODdhM2ZlODU3ZjNlNyIsICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRREFIOXNwTWkvOFR1N0Rcbms2c3V6QlZpM21hSXU2K3JsMk1NMnp4NFdGUlRQUnEwdXlxdm40bHRSWEJtVEhPU2ZXZllkSzZ6VFoyY2RWZ21cbnZmbEJsN0s2WXZIUzhTbUxPNEtOQkZsQTluMVhkTkJ3TzAwZThjTENKR1FrMGlHd3NPeXBwaGtrTVdiSUFtc2Rcbk1mMUtoMjBkU3FodGVvREVNY3BDVjVxVGJ0TVVaNGZiN1BXTnZZUjdyektaU0RkSlg4NjFidVlwcHZsWGhFNnlcbkc2NEJESytHQ2lRNzdBNGtaTXIralorN0ZsbVNOcEhhM0tPa1YvU3Ywek0rYjJEcUk1S0hyRUV6b2JsakFGSW9cbjZLOFFaMndMaWR4RjlDMEljdUVxMmp6cTVhTVE2blVjZ1RKY2srd29JeFJmM0xvdG82NUg3RHkwZUVJdHlGTzNcbjdPOFFnaHJCQWdNQkFBRUNnZ0VBRDR6VWhTNytlQjVmRUJNeVFsdjYxQ2FFNTl3WEVjZnptS2dMQUN1WURGSmJcbkNHdEl2eHBtSkxocUtxRi8rTjN2d0lnMTFxWGtLVW5NZHRCSldIclhMZzVSblRMdlJrbHNzdU5rb2svV1lSOHFcbk9zSHJVZmliNTBaTG1RNVg4enJvQzRBa2lLRWwvTzl6TE5PdHVRYWhPUzNMTFpkQ0lsUnNWdUVoSTFNNlFFR2xcbldlejk5M0g2OGhESS9VMDZONU1ZQS9OSEhwSHVGaTQ4by93K3QwWU5kdHJXaTVvdzdYWmhqRDVlaVR2UURnc0RcbjYzZGxEUVFsa3dwMDc3dGJNcWg0QzgvTDVETEVrMWRMVUpyTmFJeTFYa00wMTZpL0VveWxkTDVaNWJ5UXZFNDZcbllod0E5WUkyVmozVFFQYXVCbnFuRFBEWjRmaHBrOUcrZm1xeTlZZ2cxUUtCZ1FEbFl1WUVIVk1JMFYySXJuNUVcbkUzbzJnWGNYYnVTZ3p1TDJZMXFmT2d4V21QYitad1Npb040SDk2UHpUdldjZWh1anlnQjRnWVFiUUVtcjAyQXRcbjljdGhIRXJXemlJL1cxVFBGVVd2bUUwcDZlamVYV0xKdVlVNXJKMGZ6Z2I3UGtFK0VLUzhEWlp2bUV2T1JOQXBcblYrQlMxcXFUQ1NYZ2NMZS82cFlLRGJYNnBRS0JnUURXYWpuMDloTS9VTjcybEtTMURBZnJtdVptM1o0bmNqM0lcbkhvT2FWVWFlOTEwenUrQi9PN3IyNE01Z1I5V1k3dHFxMUllaktjQm9XSFJmRVAwdFBCbi9mc3dmMmtGZTdQL21cbjcxcTNwNmFZWERza2dBcDZNcjY2UXBuQzR5cXJSWlBySW5IdTZ2ck90YUZKRFVEajFtQyt2NVB1N09BRDhtY0xcbkNuY3hEMmZRN1FLQmdHYldLTEt0aHQxTUozZXdhdEVRUGxrVFA1WFUxRkMzajQ3UVNmOWFZYytzOGdacG51MWRcbjIweU5IQVpuWHJ0UkR2VW1DWUg4NW9IbEYySWQrRitDY3pSTkg4d2ZTOEZGcThiUERaZkVXc3V3bndLWnNVRW9cbmwrNmNVVERDQitVNUtyeXRiMzBUUmw4dlVzVGRtc2orS1laWjBNenNhL3VyN09Ud1FXV3VjZWcxQW9HQVZWcTZcbk1hclg1S2VqNnBNbnNpN1U1RlNvamFDQmVnQi9XYS9VQWRjYW91T2tCWmt2K0ZabHlpdVozRGdjYnFIL0NHeE1cbmhvWnpZdFo3bFBDbGFLRjVVLzA4OHgwbVVzeVQzbkhBTWtZYUNxTUVwRFlZZGFiSHlFd0UrOUVFeG1PUFM5Wk5cbmRxZXlLaUdoei92bnJndEVQZ3J6ci9RNkJUZzFEdThlbmJnZFFzMENnWUF6NFVjRkhBYnpYaGFXQlV5VE85YUdcbi9nQW1iaHJtYnhUZ2tpNWxwN3NTbFZHYWRFcDFMZmwwcVp3OVZqdVNyZ3JiTmJCVE9hVVVVWUQrWHpqZ3FYRmlcbi9FcjVhem1IWi9ITjlOSUFlOFJjWHZONUxQb0QydkMxWnRWbDNzZzIvTmhlS0ZpL1V5ell6cDQ5MmJQUHFweERcblpyeVJuUnU5emZYd2krOS8zN3FXMnc9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwgImNsaWVudF9lbWFpbCI6ICJnaXRodWItdXBsb2FkQHNtYXJ0LW9hc2lzLTM0MDYwMS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsICJjbGllbnRfaWQiOiAiMTEyNDI0MDEyMzU3ODgyNDIzMDgzIiwgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZ2l0aHViLXVwbG9hZCU0MHNtYXJ0LW9hc2lzLTM0MDYwMS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIgfQ=="
    #    filename: "./app-release.apk"
    #    folderId: "1pe-5f4szRLHg6CFMDAAMAVOeDop8etta"
    #    #folderId: "1kt0wzcjUZN_B3ftitmBcjqR3ZZZg2hCu"
    #    name: "simpleTest.apk"
    #    #overwrite: "true"
